### ISSUE TITLE
Edit profile - new photo

### ISSUE THREAD

**Issue by matthewerlemiller** [matthewerlemiller/projectgenesys#15]
If editing a profile and uploading a new photo, the account gets incorrectly associated with a different profiles photo. On the profile page it will show a blank photo but when checked it the photo is incorrect.

**Comment by matthewerlemiller** [comment]
After a forced browser refresh, the images are correctly associated.

**Comment by austenpayan** [comment]
@matthewerlemiller , Did you reopen this because of the "image not showing after edit" issue?

**Comment by matthewerlemiller** [comment]
I didn't mean to re-open this. I re-uploaded images like you said and it
seems to be working just fine now!

**Comment by austenpayan** [comment]
Great!
