### ISSUE TITLE
Search on "non dashboard" pages doesn't redirect to dashboard upon check in

### ISSUE THREAD

**Issue by matthewerlemiller** [matthewerlemiller/projectgenesys#16]
If you are on add student page and run a search, check someone in, you are not redirected to the dashboard afterwards

**Comment by matthewerlemiller** [comment]
The same is true on a profile page

**Comment by austenpayan** [comment]
Do we want this to redirect? I am picturing scenarios where a leader may be in the middle of inputting a new member or updating lesson logs and someone walks through the door and needs to be checked in quickly, and they can search and check in and then still be on whatever page they were on before.

What do you guys think @matthewerlemiller @AlexanderGalen ?

**Comment by matthewerlemiller** [comment]
I think that's a great point and no redirect is a good idea.
