### ISSUE TITLE
Keyboard Remains Showing Once Done Typing

### ISSUE THREAD

**Issue by matthewerlemiller** [matthewerlemiller/projectgenesys#18]
Once I click in the search field and the keyboard pops up, it won't go away without reloading the page.

**Comment by matthewerlemiller** [comment]
Or clicking a new tab in safari

**Comment by AlexanderGalen** [comment]
I'm going to try to nail this one down but it might be tricky. If i can't devise a solution before Saturday, there is always that button in the bottom right of the keyboard that hides it. if you need, you can use that method while presenting.

**Comment by matthewerlemiller** [comment]
Ok I can do that.
