### ISSUE TITLE
Database schoolID

### ISSUE THREAD

**Issue by matthewerlemiller** [matthewerlemiller/projectgenesys#38]
I am attempting to query by school ID 1-6 to re-assign the school assignments. I would like to delete schools 1 - 6 that seemed to be added for testing and are redundant now that the database has been completed. I don't know why its reporting schoolID as non-existent. Can I get a second pair of eyes on this?

Query
select \* from members where schoolId = '1'

Error
ERROR:  column "schoolid" does not exist
LINE 1: select \* from members where schoolId = '1'
                                                            ^
*********\* Error **********

**Comment by austenpayan** [comment]
This is strange. schoolId is definitely a field

**Comment by matthewerlemiller** [comment]
I found this is not an issue if I put the column in single quotes, it may be my version of PGadmin
