### ISSUE TITLE
Kickout

### ISSUE THREAD

**Issue by matthewerlemiller** [matthewerlemiller/projectgenesys#57]
Kickout functionality adds flair to members profile picture

Logs disipline in dedicated table which retains accumulated history of kickouts

kickout profile flair expires in 24 hours

**Comment by austenpayan** [comment]
For kickout flair, we have it already where the "good" flair that is next to the name will be changed to "kicked out" or "suspended", so I dont think we need to add it to the profile picture. thoughts?

**Comment by matthewerlemiller** [comment]
I've been considering this lately and I think the kickout flair has to be
on the photo as well.

A kid can only be kicked out for the day if they were already checked in.
Meaning seeing they are kicked out when searched doesn't happen often.

Also a second shift will not search a kid who is already checked in. If the
kid was kicked out first shift but returns second shift, the second shift
leader will see they are checked in on dashboard and allow them in again.

If the flair is on the dashboard pic, at a glance they will know who not to
let back in for the day.

I'm wondering if we add a attached bar underneath the pic that can have all
the flairs needed. Not sure if that would look aesthetically pleasing.
