### ISSUE TITLE
Flair Visuals

### ISSUE THREAD

**Issue by matthewerlemiller** [matthewerlemiller/projectgenesys#58]
We need to figure out a way to display many flairs to a profile pic without covering the whole pic. Flairs will be located on or around the picture so they can be seen at a glance by leaders on the dashboard.

<b>Potential flairs</b>
Checked In (this only displays on member page currently, possibly can be moved off)
Member Status (includes Jr. Staff flair)
Birthday
Kickout
Special flairs (undefined but potential)

@austenpayan @AlexanderGalen

**Comment by austenpayan** [comment]
I believe my recent addition of the flair for no permission slip took care of this issue, as we can stack these small circle badges along the bottom edge of the profile image : 
<img width="262" alt="screen shot 2016-06-04 at 12 53 23 pm" src="https://cloud.githubusercontent.com/assets/3936068/15801748/8dba49cc-2a53-11e6-9bef-88b42bfe9865.png">
